# Generated by Django 3.0.3 on 2021-08-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['pub_date']},
        ),
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.TextField(default=''),
        ),
    ]
